name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Upload artifacts  # job output 
        uses: actions/upload-artifact@v7 
        with:
          name: dist-files      # what to name it
          path: dist
          # path: |               # where to store it (can be multiple)
          #   dist
          #   package.json

          # we can download the uploaded artifacts manually from github under the wf run 
          # or use in the deploy job

  deploy:
    needs: build     # essential as we need the artifacts first
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist-files  # ensures we download the right artifacts (unzips the file)
      - name: Output contents
        run: ls             # we lose the dist folder
      - name: Deploy
        run: echo "Deploying..."
